sudo: required

services:
  - docker

script:
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - docker build -t pacdaemon/octoprint-rpi .
  - docker tag pacdaemon/octoprint-rpi pacdaemon/octoprint-rpi:latest
  - docker tag pacdaemon/octoprint-rpi pacdaemon/octoprint-rpi:1.3.8-3

deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master